apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-trading-bot
  labels:
    app: py-trading-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: py-trading-bot
  template:
    metadata:
      labels:
        pod: py-trading-bot
    spec:
      containers:
        - name: py-trading-bot
          image: py-trading-bot
          imagePullPolicy: Never
          command: [ "/bin/sh" ]
          args: ["-c", "python manage.py runserver 0.0.0.0:8000;"]
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "False"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: py-trading-bot-secret
                  key: postgres_user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: py-trading-bot-secret
                  key: postgres_password

            - name: POSTGRES_HOST
              value: py-trading-bot-postgres-service

            - name: REDIS_HOST
              value: py-trading-bot-redis-service
              
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: py-trading-bot-configmap
                  key: postgres_db 

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: py-trading-bot-secret
                  key: secret_key
                                    
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: py-trading-bot-secret
                  key: telegram_token       
                  
            - name: IB_PORT
              valueFrom:
                configMapKeyRef:
                  name: py-trading-bot-configmap
                  key: ib_port
                  
            - name: USED_API_FOR_ORDER_PERF
              valueFrom:
                configMapKeyRef:
                  name: py-trading-bot-configmap
                  key: used_api_for_order_perf
            - name: USED_API_FOR_DATA_ALERTING
              valueFrom:
                configMapKeyRef:
                  name: py-trading-bot-configmap
                  key: used_api_for_data_alerting    
            - name: USED_API_FOR_DATA_REPORTING
              valueFrom:
                configMapKeyRef:
                  name: py-trading-bot-configmap
                  key: used_api_for_data_reporting                                         
                                              
---
kind: Service
apiVersion: v1
metadata:
  name: py-trading-bot-service
spec:
  selector:
    pod: py-trading-bot
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort          
